* CSCI 77800: Ethics and Computer Science

**  Term: Fall Semester 2021

** Professor: Mike Zamansky

** Office Hours: TBD

** Email: mz631@hunter.cuny.edu

** Course Description:
*"Your scientists were so preoccupied with whether or not they could, they didn't stop to think if they should." - Jurassic Park, Michael Crichton*

Ethical concerns are frequently ignored in technical fields, but as a society we are discovering their immense importance. Algorithms can have unintended affects due to hidden bias, security and privacy can be affected negatively when decisions are made for technical merit or user convenience. Social networks have resulted in issues ranging from fake news to echo chambers and more. In this course we will explore ethical issues in computer science through a combination of programming assignments, case studies and discussions of current events.

### Expected Learning Outcomes:

#### By the end of this course, students will be able to:

1. Create programs and computer-based systems that minimize negative ethical factors such as bias and unintended consequences.

2. Create programs and computer-based systems that maximize factors including accessiblity, equity, and diversity.

3. Analyze existing computer systems to determine where factors such as bias, unintended consequences and other ethical concerns exist.

4. Understand how human factors can influence otherwise deterministic technical processes.

### Required Text: 

There is no required text for this course. Readings will be assigned from a variety of sources, as outlined in the syllabus.

** Evaluation:

- Final project/paper: 30%
- Programming assignments: 25%
- Presentations / accompanying papers / other assignments: 25%
- Weekly Ethicacy: 10%
- Class participation: 10%

** Course Content and Organization:
** Academic Integrity Statement

> "Hunter College regards acts of academic dishonesty (e.g., plagiarism,
> cheating on examinations, obtaining unfair advantage, and
> falsification of records and official documents) as serious offenses
> against the values of intellectual honesty. The College is committed
> to enforcing the CUNY Policy on Academic Integrity and will pursue
> cases of academic dishonesty according to the Hunter College Academic
> Integrity Procedures."

** ADA Statement

> "In compliance with the ADA and with Section 504 of the Rehabilitation
> Act, Hunter College is committed to ensuring educational access and
> accommodations for all its registered students. Hunter College's
> students with disabilities and medical conditions are encouraged to
> register with the Office of AccessABILITY for assistance and
> accommodation. For information and appointment contact the Office of
> AccessABILITY located in Room E1214 or call (212) 772-4857 /or TTY
> (212) 650-3230."

**Hunter Policy on Sexual Misconduct**

> "In compliance with the CUNY Policy on Sexual Misconduct, Hunter
> College reaffirms the prohibition of any sexual misconduct, which
> includes sexual violence, sexual harassment, and gender-based
> harassment retaliation against students, employees, or visitors, as
> well as certain intimate relationships. Students who have experienced
> any form of sexual violence on or off campus (including CUNY-sponsored
> trips and events) are entitled to the rights outlined in the Bill of
> Rights for Hunter College.
>
> a\. Sexual Violence: Students are strongly encouraged to immediately
> report the incident by calling 911, contacting NYPD Special Victims
> Division Hotline (646-610-7272) or their local police precinct, or
> contacting the College\'s Public Safety Office (212-772-4444).
>
> b\. All Other Forms of Sexual Misconduct: Students are also encouraged to
> contact the College\'s Title IX Campus Coordinator, Dean John Rose
> (jtrose\@hunter.cuny.edu or 212-650-3262) or Colleen Barry
> (colleen.barry\@hunter.cuny.edu or 212-772-4534) and seek complimentary
> services through the Counseling and Wellness Services Office, Hunter
> East 1123.
>
> CUNY Policy on Sexual Misconduct Link:
> <http://www.cuny.edu/about/administration/offices/la/Policy-on-SexualMisconduct-12-1-14-with-links.pdf>

** Syllabus Change Policy:

> Except for changes that substantially affect implementation of the
> evaluation (grading) statement, this syllabus is a guide for the
> course and is subject to change with advance notice
>
> Students will be informed of any changes to the class syllabus via
> direct email.
